kind: pipeline
type: docker
name: rbac
workspace:
  base: /data/service
  path: .
steps:
  - name: 部署rbac项目
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: rsa
      target:
        from_secret: /var/www/myapp/
      source: ./*
      volumes:
        - name: webroot
          host:
            path: /opt
        - name: cache
          host:
            path: /tmp/cache
      script:
        - cd /var/www/myapp/
        - pwd && ls -l
        - rm -rf dist/*
        - pwd && ls -l
        - docker build -t biz-rbac-service:0.0.1 .
        - docker rm -f biz-rbac-service || true
        - docker run -d --rm --name biz-rbac-service -p 8002:80 biz-rbac-service:0.0.1

