kind: pipeline
type: docker
name: rbac
workspace:
  base: /data/service
  path: .
steps:
  - name: 部署rbac项目
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: 119.45.142.166
      port: 22
      username:
        from_secret: username
      password:
        from_secret: rsa
      script:
        - cd /var/www/myapp
        - pwd && ls -l
        - git pull origin master
        - rm -rf dist/*
        - cnpm run build
        - pwd && ls -l
        - docker build -t rbac:v1 .
        - docker rm -f rbac || true
        - docker run -d --rm --name rbac -p 8002:80 api-ui:v1
