kind: pipeline
type: docker
name: rbac1
workspace:
  base: /data/service
  path: .
steps:
  - name: 部署rbac项目
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: rsa
      target:
        from_secret: /var/www/myapp/
      source: ./*
      volumes:
        - name: webroot
          host:
            path: /opt
        - name: cache
          host:
            path: /tmp/cache
      script:
        - cd /var/www/myapp/
        - pwd && ls -l
        - git pull origin master
        - rm -rf dist/*
        - cnpm run build
        - pwd && ls -l
        - docker build -t rbac:v1 .
        - docker rm -f rbac || true
        - docker run -d --rm --name rbac -p 8002:80 rbac:v1
        - echo "endx"

